### ISSUE TITLE
support for 1536-well plates

### ISSUE THREAD

**Issue by ejfine** [CuriBio/labware-domain-models#95]
@tannermpeterson - will you accept a pull request from @marks-res to add in support for 1536-well plates?

**Comment by eli-fine-res** [comment]
specifically the `get_row_and_column_from_well_name` doesn't currently support the row naming for 1536-well plates (which have 32 rows and so starts to use double letters like `AA`)

**Comment by jperson** [comment]
@eli-fine-res Feel free to submit a PR, the repo is open source after all, if the code looks reasonable we'll merge.

**Comment by marks-res** [comment]
I think everything looks good in CI now, can you please run the real publishing workflow now to get it into PyPI?

**Comment by jperson** [comment]
0.3.2 published to PyPI
